### ISSUE TITLE
Warning: Each child in a list should have a unique 'key' prop in Testimonial component

### ISSUE THREAD

**Issue by ManashPratimPathak** [E-cell-NITS/e-cell-website-22#77]
To fix this issue, I suggest updating the Testimonial component to add a unique "key" prop for each child element in a list.

`react_devtools_backend.js:2655 Warning: Each child in a list should have a unique key prop.
Check the render method of Testimonial. See https://reactjs.org/link/warning-keys for more information.
    at Testimonial (http://localhost:3000/static/js/bundle.js:3945:69)
    at Home (http://localhost:3000/static/js/bundle.js:10975:51)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:309123:5)
    at Routes (http://localhost:3000/static/js/bundle.js:309545:5)
    at Scrolling (http://localhost:3000/static/js/bundle.js:10007:77)
    at Router (http://localhost:3000/static/js/bundle.js:309483:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:307841:5)
    at App`

**Comment by ManashPratimPathak** [comment]
@hereisadi also add designation under their names

**Comment by hereisadi** [comment]
PR #78
